### ISSUE TITLE
jMAVSim doesn't run with Java 10

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#10443]
As already mentioned in several issues, jMAVSim does not run correctly with Java 10.

```
BUILD SUCCESSFUL
Total time: 3 seconds
Exception in thread "main" java.lang.NoClassDefFoundError: javax/vecmath/Tuple3d
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:374)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: javax.vecmath.Tuple3d
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 3 more
Exception in thread "main" java.lang.NoClassDefFoundError: javax/vecmath/Tuple3d
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:374)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: javax.vecmath.Tuple3d
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 3 more
```

The workaround is to go back to Java 8 for now. Make sure java 8 is installed, then do:

```
rm -rf Tools/jMAVSim/out
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
make posix jmavsim
```

This came up first here:
http://discuss.px4.io/t/problem-running-jmavsim-on-macos-high-sierra/5357

This is tracked here as well: https://github.com/hharrison/vecmath/issues/7

**Comment by roseyangyu** [comment]
This is helpful
