### ISSUE TITLE
compile error:No such file or directory: '.../Firmware/src/drivers/uavcan/libuavcan/libuavcan/../dsdl/uavcan'

### ISSUE THREAD

**Issue by AlexLuya** [PX4/Firmware#11581]
My configuration:

ubuntu     18.04 64bit
firmware master(latest) commit 468fb53459e9760f6f5a288a061a21133357872d

I have:

```
source ubuntu_sim.sh
git pull
git submodule update
```

when:

`make -j `nproc` px4fmu-v5_default`

got this error:

```
[18/1173] git submodule mavlink/include/mavlink/v2.0
[20/1173] Running dsdl compiler
FAILED: libuavcan_dsdlc_run.stamp 
cd /home/alex/workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan && /usr/bin/python /home/alex/workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan/dsdl_compiler/libuavcan_dsdlc test/dsdl_test/root_ns_a test/dsdl_test/root_ns_b /home/alex/workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan/../dsdl/uavcan -Oinclude/dsdlc_generated && /usr/bin/cmake -E touch /home/alex/workspace/Firmware/build/px4_fmu-v5_default/libuavcan_dsdlc_run.stamp
Compiler failure
Traceback (most recent call last):
  File "/home/alex/workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan/dsdl_compiler/libuavcan_dsdlc", line 61, in <module>
    dsdlc_run(args.source_dir, args.incdir, args.outdir)
  File "/home/alex/workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 58, in run
    types = run_parser(source_dirs, include_dirs + source_dirs)
  File ".../workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 97, in run_parser
    die(ex)
  File "..../workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 90, in die
    raise DsdlCompilerException(str(text))
DsdlCompilerException: OS error in [..../workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan/../dsdl/uavcan]: [Errno 2] No such file or directory: '/home/alex/workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan/../dsdl/uavcan'
OS error in [/home/alex/workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan/../dsdl/uavcan]: [Errno 2] No such file or directory: '/home/alex/workspace/Firmware/src/drivers/uavcan/libuavcan/libuavcan/../dsdl/uavcan'
[23/1173] Generating nuttx/include/nuttx/version.h, nuttx/include/nuttx/config.h
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[25/1173] Performing configure step for 'px4io_firmware'
-- PX4 config file: /home/alex/workspace/Firmware/boards/px4/io-v2/default.cmake
```
Please tell me how to fix this issue,thanks

**Comment by julianoes** [comment]
Have you tried `make distclean`? Is this still an issue?
