### ISSUE TITLE
Cannot set parameter to 0. 'Param types mismatch'

### ISSUE THREAD

**Issue by jowaibel** [PX4/Firmware#14311]
**Describe the bug**
I'm not sure if this is a mavros or px4 issue. That's why I post it on both repos.

It probably appeared for the first time after having updated to PX4 v.1.10.1 stable. I cannot set anymore a parameter to the value 0 via the mavparam set command/service. Any other (non-zero) value works.
I tried different parameters, standard and custom ones, their type is float, for example FW_T_RC.
It is however possible to set the param to 0 using QGroundControl.

Running mavparam on the console gives:
```
rosrun mavros mavparam set FW_R_TC 0.0

Traceback (most recent call last):
  File "/opt/ros/melodic/lib/mavros/mavparam", line 104, in <module>
    main()
  File "/opt/ros/melodic/lib/mavros/mavparam", line 100, in main
    args.func(args)
  File "/opt/ros/melodic/lib/mavros/mavparam", line 63, in do_set
    print(param_set(args.param_id, val))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/mavros/param.py", line 149, in param_set
    raise IOError("Request failed.")
IOError: Request failed.
```

Same for this call:

```
rosservice call /mavros/param/set "param_id: 'FW_R_TC'
value:
  integer: 0
  real: 0.0" 
success: False
value: 
  integer: 0
  real: 0.40000000596
```

**To Reproduce**
1. Connect to pixhawk via mavros: roslaunch mavros px4.launch
2. Change a parameter to zero, running: rosrun mavros mavparam set FW_R_TC 0.0

**Expected behavior**
Parameter should be set to zero.

**Log Files and Screenshots**
```
[ INFO] [1583486234.867191312]: FCU: [pm] param types mismatch param: FW_R_TC
[ WARN] [1583486235.849716948]: PR: Resend param set for FW_R_TC, retries left 2
[ INFO] [1583486235.864053146]: FCU: [pm] param types mismatch param: FW_R_TC
[ WARN] [1583486236.850380930]: PR: Resend param set for FW_R_TC, retries left 1
[ INFO] [1583486236.865401528]: FCU: [pm] param types mismatch param: FW_R_TC
[ WARN] [1583486237.851102954]: PR: Resend param set for FW_R_TC, retries left 0
[ INFO] [1583486237.861824126]: FCU: [pm] param types mismatch param: FW_R_TC
[ERROR] [1583486238.851263943]: PR: Param set for FW_R_TC timed out.
```

```
rosrun mavros mavparam set FW_R_TC 0.0
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/mavros/mavparam", line 104, in <module>
    main()
  File "/opt/ros/melodic/lib/mavros/mavparam", line 100, in main
    args.func(args)
  File "/opt/ros/melodic/lib/mavros/mavparam", line 63, in do_set
    print(param_set(args.param_id, val))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/mavros/param.py", line 149, in param_set
    raise IOError("Request failed.")
IOError: Request failed.

```

**Comment by julianoes** [comment]
FYI @TSC21
