### ISSUE TITLE
Error: sdlog2 format for IMU is incorrect

### ISSUE THREAD

**Issue by HesselM** [PX4/Firmware#1958]
The sdlog2 message format for the IMU is missing 2 floating point place holders, resulting in a parse error when using the python parser.

```
python sdlog2_dump.py log001.px4log -f "export.csv" -t "TIME" -d "," -n ""
Traceback (most recent call last):
  File "sdlog2_dump.py", line 334, in <module>
    _main()
  File "sdlog2_dump.py", line 331, in _main
    parser.process(fn)
  File "sdlog2_dump.py", line 154, in process
    self.__parseMsg(msg_descr)
  File "sdlog2_dump.py", line 242, in __parseMsg
    data = list(struct.unpack(msg_struct, str(self.__buffer[self.__ptr+self.MSG_HEADER_LEN:self.__ptr+msg_length])))
```

Wrong message format:
https://github.com/PX4/Firmware/tree/master/src/modules/sdlog2/sdlog2_messages.h#L477-L479

**Comment by LorenzMeier** [comment]
Fixed, closing.
