### ISSUE TITLE
Segfault in sdlog2 running in SITL

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3895]
Just testing out ROS + Gazebo + SITL in a Docker container. It works if I comment out this line: https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2.c#L477

Otherwise I get this:

```
WARN  stream OPTICAL_FLOW_RAD on UDP port 14556 enabled with rate 10.0 Hz


[New Thread 0x2aaaaab16700 (LWP 3586)]
WARN  log buffer size: 8192 bytes
telem> 
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x2aaaaab16700 (LWP 3586)]
buffered_vfprintf (s=s@entry=0x2aaaababf1c0 <_IO_2_1_stderr_>, format=format@entry=0x4ed865 "[blackbox] %s", args=args@entry=0x2aaaaab15738)
    at vfprintf.c:2335
2335    vfprintf.c: No such file or directory.
(gdb) bt
#0  buffered_vfprintf (s=s@entry=0x2aaaababf1c0 <_IO_2_1_stderr_>, format=format@entry=0x4ed865 "[blackbox] %s", args=args@entry=0x2aaaaab15738)
    at vfprintf.c:2335
#1  0x00002aaaab749eae in _IO_vfprintf_internal (s=s@entry=0x2aaaababf1c0 <_IO_2_1_stderr_>, format=0x4ed865 "[blackbox] %s", ap=ap@entry=0x2aaaaab15738)
    at vfprintf.c:1313
#2  0x00002aaaab809565 in ___fprintf_chk (fp=0x2aaaababf1c0 <_IO_2_1_stderr_>, flag=1, format=<optimized out>) at fprintf_chk.c:35
#3  0x00000000004a972a in fprintf (__fmt=<optimized out>, __stream=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/stdio2.h:97
#4  create_log_dir () at /data/UAV/ros-src/Firmware/src/modules/sdlog2/sdlog2.c:477
#5  sdlog2_start_log () at /data/UAV/ros-src/Firmware/src/modules/sdlog2/sdlog2.c:704
#6  0x00000000004aa0a7 in sdlog2_thread_main (argc=<optimized out>, argv=0x730ac8) at /data/UAV/ros-src/Firmware/src/modules/sdlog2/sdlog2.c:1329
#7  0x000000000042c03f in entry_adapter (ptr=0x730aa0) at /data/UAV/ros-src/Firmware/src/platforms/posix/px4_layer/px4_posix_tasks.cpp:103
#8  0x00002aaaaacd8182 in start_thread (arg=0x2aaaaab16700) at pthread_create.c:312
#9  0x00002aaaab7fa47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

```

Does that sound familiar to someone?

**Comment by AndreasAntener** [comment]
Not a problem anymore on master
