### ISSUE TITLE
Simulator: Address sanitizer corner case

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6078]
```
INFO  [simulator] Got initial simuation data, running sim..
ASAN:DEADLYSIGNAL
=================================================================
==56078==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010efff62e bp 0x70000c42d940 sp 0x70000c42d850 T6)
    #0 0x10efff62d in uORB::DeviceNode::publish(orb_metadata const*, void*, void const*) uORBDevices.cpp:428
    #1 0x10eff47a8 in uORB::Manager::orb_publish(orb_metadata const*, void*, void const*) uORBManager.cpp:250
    #2 0x10efe85ac in orb_publish uORB.cpp:89
    #3 0x10efe855f in orb_publish_auto uORB.cpp:81
    #4 0x10efbbb4d in Simulator::handle_message(__mavlink_message*, bool) simulator_mavlink.cpp:460
    #5 0x10efc4574 in Simulator::pollForMAVLinkMessages(bool, int) simulator_mavlink.cpp:779
    #6 0x10efb0daf in Simulator::start(int, char**) simulator.cpp:142
    #7 0x10ec9dbe4 in entry_adapter(void*) px4_posix_tasks.cpp:105
    #8 0x7fffbaaebaaa in _pthread_body (libsystem_pthread.dylib+0x3aaa)
    #9 0x7fffbaaeb9f6 in _pthread_start (libsystem_pthread.dylib+0x39f6)
    #10 0x7fffbaaeb220 in thread_start (libsystem_pthread.dylib+0x3220)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV uORBDevices.cpp:428 in uORB::DeviceNode::publish(orb_metadata const*, void*, void const*)
Thread T6 created by T0 here:
    #0 0x10f9ed379 in wrap_pthread_create (libclang_rt.asan_osx_dynamic.dylib+0x41379)
    #1 0x10ec9d788 in px4_task_spawn_cmd px4_posix_tasks.cpp:246
    #2 0x10efb10e1 in simulator_main simulator.cpp:193
    #3 0x10ebfe858 in run_cmd(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, bool, bool) main.cpp:219
    #4 0x10ebfd53b in process_line(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool) main.cpp:260
    #5 0x10ebf4a83 in main main.cpp:460
    #6 0x7fffba8d4254 in start (libdyld.dylib+0x5254)

==56078==ABORTING
/src/Firmware/Tools/sitl_run.sh: line 140: 56078 Abort trap: 6           $sitl_command
```

@bkueng Fail location is here:

```C++
	/* this is a bit risky, since we are trusting the handle in order to deref it */
	if (devnode->_meta != meta) {
		errno = EINVAL;
		return ERROR;
	}
```

**Comment by LorenzMeier** [comment]
@kd0aij This was the result of the ground truth handle not being initialised in the constructor. Fixed in ce136d7.
