### ISSUE TITLE
Out-of-tree module build is broken

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#7409]
I was trying out the out-of-tree module build functionality (https://dev.px4.io/en/advanced/out_of_tree_modules.html), but it seems to be broken at the moment. I suspect that this is due to the recent param parser refactoring.

```
Mohammeds-MacBook-Pro:Firmware kabir$ make px4fmu-v3_default EXTERNAL_MODULES_LOCATION=/Users/kabir/Development/PX4/uasys-px4-modules
-- CMAKE_MODULE_PATH: /Users/kabir/Development/PX4/Firmware/cmake
-- Nuttx build for px4fmu-v3 on m4 hardware, using nsh with ROMFS on px4fmu_common
-- Build Type: MinSizeRel
-- PX4 VERSION: v1.6.2-37-ge6159d9e5
-- CONFIG: nuttx-px4fmu-v3-default
CMake Deprecation Warning at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/CMakeForceCompiler.cmake:69 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/toolchains/Toolchain-arm-none-eabi.cmake:31 (cmake_force_c_compiler)
  /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/CMakeDetermineSystem.cmake:88 (include)
  CMakeLists.txt:273 (project)


CMake Deprecation Warning at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/CMakeForceCompiler.cmake:83 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/toolchains/Toolchain-arm-none-eabi.cmake:37 (cmake_force_cxx_compiler)
  /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/CMakeDetermineSystem.cmake:88 (include)
  CMakeLists.txt:273 (project)


CMake Deprecation Warning at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/CMakeForceCompiler.cmake:69 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/toolchains/Toolchain-arm-none-eabi.cmake:31 (cmake_force_c_compiler)
  build_px4fmu-v3_default/CMakeFiles/3.8.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:273 (project)


CMake Deprecation Warning at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/CMakeForceCompiler.cmake:83 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/toolchains/Toolchain-arm-none-eabi.cmake:37 (cmake_force_cxx_compiler)
  build_px4fmu-v3_default/CMakeFiles/3.8.2/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:273 (project)


-- The ASM compiler identification is GNU
-- Found assembler: /usr/local/bin/arm-none-eabi-gcc
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.13") 
-- Found PY_jinja2: /usr/local/lib/python2.7/site-packages/jinja2  
-- C compiler: arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
-- C++ compiler: arm-none-eabi-g++ (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
-- External modules: /Users/kabir/Development/PX4/uasys-px4-modules
-- Using C++03
-- Release build type: MinSizeRel
-- Adding UAVCAN STM32 platform driver
-- Adding ROMFS on px4fmu-v3
-- Nuttx build for px4fmu-v3 on m3 hardware, using nsh 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/kabir/Development/PX4/Firmware/build_px4fmu-v3_default
[12/766] Generating ../../../../parameters.xml
FAILED: parameters.xml 
cd /Users/kabir/Development/PX4/Firmware/build_px4fmu-v3_default && /usr/local/bin/python /Users/kabir/Development/PX4/Firmware/Tools/px_process_params.py -s /Users/kabir/Development/PX4/Firmware/src/drivers/airspeed /Users/kabir/Development/PX4/Firmware/src/drivers/blinkm /Users/kabir/Development/PX4/Firmware/src/drivers/bmi160 /Users/kabir/Development/PX4/Firmware/src/drivers/bmp280 /Users/kabir/Development/PX4/Firmware/src/drivers/boards/px4fmu-v2 /Users/kabir/Development/PX4/Firmware/src/drivers/bst /Users/kabir/Development/PX4/Firmware/src/drivers/camera_trigger /Users/kabir/Development/PX4/Firmware/src/drivers/device /Users/kabir/Development/PX4/Firmware/src/drivers/ets_airspeed /Users/kabir/Development/PX4/Firmware/src/drivers/frsky_telemetry /Users/kabir/Development/PX4/Firmware/src/drivers/gps /Users/kabir/Development/PX4/Firmware/src/drivers/hmc5883 /Users/kabir/Development/PX4/Firmware/src/drivers/hott /Users/kabir/Development/PX4/Firmware/src/drivers/hott/hott_sensors /Users/kabir/Development/PX4/Firmware/src/drivers/hott/hott_telemetry /Users/kabir/Development/PX4/Firmware/src/drivers/iridiumsbd /Users/kabir/Development/PX4/Firmware/src/drivers/l3gd20 /Users/kabir/Development/PX4/Firmware/src/drivers/led /Users/kabir/Development/PX4/Firmware/src/drivers/lis3mdl /Users/kabir/Development/PX4/Firmware/src/drivers/ll40ls /Users/kabir/Development/PX4/Firmware/src/drivers/lsm303d /Users/kabir/Development/PX4/Firmware/src/drivers/mb12xx /Users/kabir/Development/PX4/Firmware/src/drivers/meas_airspeed /Users/kabir/Development/PX4/Firmware/src/drivers/mkblctrl /Users/kabir/Development/PX4/Firmware/src/drivers/mpu6000 /Users/kabir/Development/PX4/Firmware/src/drivers/mpu9250 /Users/kabir/Development/PX4/Firmware/src/drivers/ms5611 /Users/kabir/Development/PX4/Firmware/src/drivers/oreoled /Users/kabir/Development/PX4/Firmware/src/drivers/pwm_input /Users/kabir/Development/PX4/Firmware/src/drivers/pwm_out_sim /Users/kabir/Development/PX4/Firmware/src/drivers/px4flow /Users/kabir/Development/PX4/Firmware/src/drivers/px4fmu /Users/kabir/Development/PX4/Firmware/src/drivers/px4io /Users/kabir/Development/PX4/Firmware/src/drivers/rgbled /Users/kabir/Development/PX4/Firmware/src/drivers/sf0x /Users/kabir/Development/PX4/Firmware/src/drivers/sf1xx /Users/kabir/Development/PX4/Firmware/src/drivers/snapdragon_rc_pwm /Users/kabir/Development/PX4/Firmware/src/drivers/srf02 /Users/kabir/Development/PX4/Firmware/src/drivers/stm32 /Users/kabir/Development/PX4/Firmware/src/drivers/stm32/adc /Users/kabir/Development/PX4/Firmware/src/drivers/stm32/tone_alarm /Users/kabir/Development/PX4/Firmware/src/drivers/tap_esc /Users/kabir/Development/PX4/Firmware/src/drivers/trone /Users/kabir/Development/PX4/Firmware/src/drivers/vmount /Users/kabir/Development/PX4/Firmware/src/modules/sensors /Users/kabir/Development/PX4/Firmware/src/systemcmds/bl_update /Users/kabir/Development/PX4/Firmware/src/systemcmds/config /Users/kabir/Development/PX4/Firmware/src/systemcmds/dumpfile /Users/kabir/Development/PX4/Firmware/src/systemcmds/esc_calib /Users/kabir/Development/PX4/Firmware/src/systemcmds/hardfault_log /Users/kabir/Development/PX4/Firmware/src/systemcmds/led_control /Users/kabir/Development/PX4/Firmware/src/systemcmds/mixer /Users/kabir/Development/PX4/Firmware/src/systemcmds/motor_ramp /Users/kabir/Development/PX4/Firmware/src/systemcmds/mtd /Users/kabir/Development/PX4/Firmware/src/systemcmds/nshterm /Users/kabir/Development/PX4/Firmware/src/systemcmds/param /Users/kabir/Development/PX4/Firmware/src/systemcmds/perf /Users/kabir/Development/PX4/Firmware/src/systemcmds/pwm /Users/kabir/Development/PX4/Firmware/src/systemcmds/reboot /Users/kabir/Development/PX4/Firmware/src/systemcmds/sd_bench /Users/kabir/Development/PX4/Firmware/src/systemcmds/top /Users/kabir/Development/PX4/Firmware/src/systemcmds/topic_listener /Users/kabir/Development/PX4/Firmware/src/systemcmds/ver /Users/kabir/Development/PX4/Firmware/src/drivers/sf0x/sf0x_tests /Users/kabir/Development/PX4/Firmware/src/drivers/test_ppm /Users/kabir/Development/PX4/Firmware/src/modules/commander/commander_tests /Users/kabir/Development/PX4/Firmware/src/lib/controllib/controllib_test /Users/kabir/Development/PX4/Firmware/src/modules/mavlink/mavlink_tests /Users/kabir/Development/PX4/Firmware/src/modules/mc_pos_control/mc_pos_control_tests /Users/kabir/Development/PX4/Firmware/src/modules/unit_test /Users/kabir/Development/PX4/Firmware/src/modules/uORB/uORB_tests /Users/kabir/Development/PX4/Firmware/src/systemcmds/tests /Users/kabir/Development/PX4/Firmware/src/modules/commander /Users/kabir/Development/PX4/Firmware/src/modules/events /Users/kabir/Development/PX4/Firmware/src/modules/gpio_led /Users/kabir/Development/PX4/Firmware/src/modules/land_detector /Users/kabir/Development/PX4/Firmware/src/modules/load_mon /Users/kabir/Development/PX4/Firmware/src/modules/mavlink /Users/kabir/Development/PX4/Firmware/src/modules/navigator /Users/kabir/Development/PX4/Firmware/src/modules/uavcan /Users/kabir/Development/PX4/Firmware/src/modules/camera_feedback /Users/kabir/Development/PX4/Firmware/src/modules/attitude_estimator_q /Users/kabir/Development/PX4/Firmware/src/modules/ekf2 /Users/kabir/Development/PX4/Firmware/src/modules/local_position_estimator /Users/kabir/Development/PX4/Firmware/src/modules/position_estimator_inav /Users/kabir/Development/PX4/Firmware/src/modules/fw_att_control /Users/kabir/Development/PX4/Firmware/src/modules/fw_pos_control_l1 /Users/kabir/Development/PX4/Firmware/src/modules/gnd_att_control /Users/kabir/Development/PX4/Firmware/src/modules/gnd_pos_control /Users/kabir/Development/PX4/Firmware/src/modules/mc_att_control /Users/kabir/Development/PX4/Firmware/src/modules/mc_pos_control /Users/kabir/Development/PX4/Firmware/src/modules/vtol_att_control /Users/kabir/Development/PX4/Firmware/src/modules/logger /Users/kabir/Development/PX4/Firmware/src/modules/sdlog2 /Users/kabir/Development/PX4/Firmware/src/modules/dataman /Users/kabir/Development/PX4/Firmware/src/modules/systemlib/param /Users/kabir/Development/PX4/Firmware/src/modules/systemlib /Users/kabir/Development/PX4/Firmware/src/modules/systemlib/mixer /Users/kabir/Development/PX4/Firmware/src/modules/uORB /Users/kabir/Development/PX4/Firmware/src/lib/controllib /Users/kabir/Development/PX4/Firmware/src/lib/conversion /Users/kabir/Development/PX4/Firmware/src/lib/DriverFramework/framework /Users/kabir/Development/PX4/Firmware/src/lib/ecl /Users/kabir/Development/PX4/Firmware/src/lib/external_lgpl /Users/kabir/Development/PX4/Firmware/src/lib/geo /Users/kabir/Development/PX4/Firmware/src/lib/geo_lookup /Users/kabir/Development/PX4/Firmware/src/lib/launchdetection /Users/kabir/Development/PX4/Firmware/src/lib/led /Users/kabir/Development/PX4/Firmware/src/lib/mathlib /Users/kabir/Development/PX4/Firmware/src/lib/mathlib/math/filter /Users/kabir/Development/PX4/Firmware/src/lib/runway_takeoff /Users/kabir/Development/PX4/Firmware/src/lib/tailsitter_recovery /Users/kabir/Development/PX4/Firmware/src/lib/terrain_estimation /Users/kabir/Development/PX4/Firmware/src/lib/version /Users/kabir/Development/PX4/Firmware/src/platforms/common /Users/kabir/Development/PX4/Firmware/src/platforms/nuttx /Users/kabir/Development/PX4/Firmware/src/platforms/nuttx/px4_layer /Users/kabir/Development/PX4/Firmware/src/modules/bottle_drop /Users/kabir/Development/PX4/Firmware/src/examples/rover_steering_control /Users/kabir/Development/PX4/Firmware/src/examples/segway /Users/kabir/Development/PX4/Firmware/src/examples/px4_simple_app /Users/kabir/Development/PX4/Firmware/src/examples/px4_daemon_app /Users/kabir/Development/PX4/Firmware/src/examples/px4_mavlink_debug /Users/kabir/Development/PX4/Firmware/src/examples/fixedwing_control /Users/kabir/Development/PX4/Firmware/src/examples/hwtest /Users/kabir/Development/PX4/Firmware/src/examples/ekf_att_pos_estimator /Users/kabir/Development/PX4/Firmware/src//Users/kabir/Development/PX4/uasys-px4-modules/src/drivers/camera_trigger /Users/kabir/Development/PX4/uasys-px4-modules --board CONFIG_ARCH_px4fmu-v3 --xml --inject-xml --overrides {}
Traceback (most recent call last):
  File "/Users/kabir/Development/PX4/Firmware/Tools/px_process_params.py", line 199, in <module>
    main()
  File "/Users/kabir/Development/PX4/Firmware/Tools/px_process_params.py", line 145, in main
    if not scanner.ScanDir(args.src_path, parser):
  File "/Users/kabir/Development/PX4/Firmware/Tools/px4params/srcscanner.py", line 20, in ScanDir
    for filename in os.listdir(srcdir):
OSError: [Errno 2] No such file or directory: '/Users/kabir/Development/PX4/Firmware/src//Users/kabir/Development/PX4/uasys-px4-modules/src/drivers/camera_trigger'
[14/766] Copying NuttX for px4fmu-v3 with nsh
ninja: build stopped: subcommand failed.
make: *** [px4fmu-v3_default] Error 1
Mohammeds-MacBook-Pro:Firmware kabir$ 

```

**Comment by dagar** [comment]
Sorry, should be quick to fix though.
Can you roughly list the layout of the out of tree portion?

**Comment by mhkabir** [comment]
Yeah, so the root directory is `/Users/kabir/Development/PX4/uasys-px4-modules`. It contains a directory `src`, which contains a `CMakeLists.txt` (see below) and a `drivers` directory.
I'm just trying to build the unmodified camera trigger driver from Firmware. It is located at `/Users/kabir/Development/PX4/uasys-px4-modules/src/drivers/camera_trigger`.

`CMakeLists.txt` : 

```
set(config_module_list_external
    drivers/camera_trigger
    PARENT_SCOPE
    )
```

**Comment by LorenzMeier** [comment]
Fixed by Beat.
