### ISSUE TITLE
MAC: can not SITL SUCCESSFUL

### ISSUE THREAD

**Issue by huangwen0907** [PX4/Firmware#9311]
@LorenzMeier @julianoes Hi, Now I have a problem of SITL in my MAC, my error comes out after I `make posix jmavsim`. Could you please help solve this bug? Thank you

There are some related issues: #9145 #9042 

Now my java version is
>java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)

The build error:
>BUILD SUCCESSFUL
Total time: 1 second
Exception in thread "main" java.lang.NoClassDefFoundError: javax/vecmath/Tuple3d
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:374)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: javax.vecmath.Tuple3d
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 3 more
Exception in thread "main" java.lang.NoClassDefFoundError: javax/vecmath/Tuple3d
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:374)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: javax.vecmath.Tuple3d
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 3 more

**Comment by julianoes** [comment]
@huangwen0907 this usually happens when you are using Java 9 or 10. You need to make sure Java 8 is installed and then do:
```
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
```

For more discussion, check:
http://discuss.px4.io/t/problem-running-jmavsim-on-macos-high-sierra/5357/2

**Comment by huangwen0907** [comment]
@julianoes Thanks a lot for your suggestion. I will have a try.
