### ISSUE TITLE
Firmware/Tools/sitl_run.sh: line 167: kill: (20235) - No such process

### ISSUE THREAD

**Issue by gbaweja** [PX4/Firmware#9507]
```
[1/2] cd /Users/govinda/Desktop/Firmware/build/posix_sit.../Users/govinda/Desktop/Firmware/build/posix_sitl_defaul
args: /Users/govinda/Desktop/Firmware/build/posix_sitl_default/px4 posix-configs/SITL/init/ekf2 none jmavsim none /Users/govinda/Desktop/Firmware /Users/govinda/Desktop/Firmware/build/posix_sitl_default
SITL ARGS
sitl_bin: /Users/govinda/Desktop/Firmware/build/posix_sitl_default/px4
rcS_dir: posix-configs/SITL/init/ekf2
debugger: none
program: jmavsim
model: none
src_path: /Users/govinda/Desktop/Firmware
build_path: /Users/govinda/Desktop/Firmware/build/posix_sitl_default
empty model, setting iris as default
SITL COMMAND: /Users/govinda/Desktop/Firmware/build/posix_sitl_default/px4 /Users/govinda/Desktop/Firmware /Users/govinda/Desktop/Firmware/posix-configs/SITL/init/ekf2/iris
data path: /Users/govinda/Desktop/Firmware
commands file: /Users/govinda/Desktop/Firmware/posix-configs/SITL/init/ekf2/iris

- - -
| ___ \ \ \ / / / |
| |_/ / \ V / / /| |
| __/ / \ / /_| |
| | / /^\ \ \___ |
\_| \/ \/ |_/

px4 starting.

INFO [dataman] Unknown restart, data manager file 'rootfs/fs/microsd/dataman' size is 11405132 bytes
INFO [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..
Buildfile: /Users/govinda/Desktop/Firmware/Tools/jMAVSim/build.xml

make_dirs:

compile:

create_run_jar:

copy_res:

BUILD SUCCESSFUL
Total time: 0 seconds
Exception in thread "main" java.lang.NoClassDefFoundError: javax/vecmath/Tuple3d
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:374)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: javax.vecmath.Tuple3d
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 3 more
Exception in thread "main" java.lang.NoClassDefFoundError: javax/vecmath/Tuple3d
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:374)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: javax.vecmath.Tuple3d
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 3 more
```

**Comment by julianoes** [comment]
This looks the same as what is discussed here:
http://discuss.px4.io/t/problem-running-jmavsim-on-macos-high-sierra/5357/23

Can you check if this works:
```
rm -rf Tools/jMAVSim/out/
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
```

And then build again in the same console.
